name: Scrape SaveAI Locations

on:
  push:
    paths:
      - 'locations.md'
      - 'world_map.ipynb'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'  # Specify the Python version you need

    - name: Install dependencies
      run: |
        pip install geopy folium # Add other dependencies as needed

    - name: Generate the map
      run: |
        python world_map.py

    - name: Commit changes
      run: |
        git config user.name "github-actions[bot]"
        git config user.email "github-actions[bot]@users.noreply.github.com"
        git add .
        git commit -m "Automated update of Save the AI locations" || echo "No changes to commit"
        git push
